In [1]:
import torch

In [3]:
torch.Size([5,3])

torch.Size([5, 3])

In [5]:
x = torch.rand(5, 3)
x

tensor([[0.8876, 0.1127, 0.9622],
        [0.8890, 0.4773, 0.6641],
        [0.5796, 0.9008, 0.5248],
        [0.2270, 0.5382, 0.3205],
        [0.2546, 0.6870, 0.5194]])

In [4]:
y = torch.rand(5, 3)
y

tensor([[0.9989, 0.1763, 0.1203],
        [0.6723, 0.7861, 0.1038],
        [0.2403, 0.5675, 0.5177],
        [0.0192, 0.0014, 0.6062],
        [0.5780, 0.8747, 0.5314]])

In [6]:
torch.add(x,y)

tensor([[1.8865, 0.2889, 1.0825],
        [1.5612, 1.2634, 0.7679],
        [0.8199, 1.4684, 1.0424],
        [0.2462, 0.5396, 0.9267],
        [0.8326, 1.5616, 1.0508]])

In [7]:
x+y

tensor([[1.8865, 0.2889, 1.0825],
        [1.5612, 1.2634, 0.7679],
        [0.8199, 1.4684, 1.0424],
        [0.2462, 0.5396, 0.9267],
        [0.8326, 1.5616, 1.0508]])

In [8]:
x.add(y)

tensor([[1.8865, 0.2889, 1.0825],
        [1.5612, 1.2634, 0.7679],
        [0.8199, 1.4684, 1.0424],
        [0.2462, 0.5396, 0.9267],
        [0.8326, 1.5616, 1.0508]])

In [ ]:
# 任何使张量发生变化的操作都有一个后缀'_', 例如: x.copy_(y)

In [9]:
x.copy_(y)
x

tensor([[0.9989, 0.1763, 0.1203],
        [0.6723, 0.7861, 0.1038],
        [0.2403, 0.5675, 0.5177],
        [0.0192, 0.0014, 0.6062],
        [0.5780, 0.8747, 0.5314]])

In [10]:
x[:,1]

tensor([0.1763, 0.7861, 0.5675, 0.0014, 0.8747])

In [12]:
x.view(-1,5)

tensor([[0.9989, 0.1763, 0.1203, 0.6723, 0.7861],
        [0.1038, 0.2403, 0.5675, 0.5177, 0.0192],
        [0.0014, 0.6062, 0.5780, 0.8747, 0.5314]])

In [17]:
x.view(-1)

tensor([0.9989, 0.1763, 0.1203, 0.6723, 0.7861, 0.1038, 0.2403, 0.5675, 0.5177,
        0.0192, 0.0014, 0.6062, 0.5780, 0.8747, 0.5314])

In [24]:
x

tensor([[0.9989, 0.1763, 0.1203],
        [0.6723, 0.7861, 0.1038],
        [0.2403, 0.5675, 0.5177],
        [0.0192, 0.0014, 0.6062],
        [0.5780, 0.8747, 0.5314]])

In [25]:
x[0,0].item()

0.9988824129104614

In [28]:
torch.tensor([0.9422])

tensor([0.9422])

In [29]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [30]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [31]:
y.grad_fn

In [32]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [33]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [34]:
out.backward()

In [35]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [36]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 1300.5389,   389.1753, -1107.7632], grad_fn=<MulBackward0>)


In [37]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [38]:

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
